import React, { useState, useMemo } from "react";
import "./AdminDash.css"; 
import { toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const ICONS = {
  search: <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="m21 21-4.34-4.34"/><circle cx="11" cy="11" r="8"/></svg>,
  eye: <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg>,
  ban: <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"/><path d="m4.9 4.9 14.2 14.2"/></svg>,
  close: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M18 6 6 18"/><path d="m6 6 12 12"/></svg>,
  flag: <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"><path d="M4 15s1-1 4-1 5 2 8 2 4-1 4-1V3s-1 1-4 1-5-2-8-2-4 1-4 1z"/><line x1="4" x2="4" y1="22" y2="15"/></svg>,
  check: <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><polyline points="20 6 9 17 4 12"/></svg>,
  link: <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71"/></svg>
};

// Mock data representing the queue of reports generated by Faculty
const mockReports = [
  { 
    id: "rep1", 
    student: { name: "Aman Gupta", rollNo: "22CS014", dept: "CSE" }, 
    faculty: "Prof. Alok Sharma", 
    category: "Plagiarism", 
    assignment: "DS Assignment 3: Sorting Algorithms",
    remarks: "Student copied the exact quicksort implementation from an external source, including the specific variable names and comments not taught in this module.", 
    date: "April 13, 2026" 
  },
  { 
    id: "rep2", 
    student: { name: "Priya Verma", rollNo: "21IT018", dept: "IT" }, 
    faculty: "Dr. Sunita Verma", 
    category: "Inappropriate Content", 
    assignment: "Web Dev Final Project",
    remarks: "The submitted project files contained inappropriate, non-academic images embedded within the assets folder.", 
    date: "April 12, 2026" 
  },
  { 
    id: "rep3", 
    student: { name: "Vikram Kumar", rollNo: "21CS099", dept: "CSE" }, 
    faculty: "Ms. Neha Gupta", 
    category: "Abusive Language", 
    assignment: "Peer Review: Database Schema",
    remarks: "Student used highly offensive language directed at another student in the peer-review comment section.", 
    date: "April 10, 2026" 
  },
];

const TABLE_HEADERS = [
  { label: "Reported Student", cls: "ps-4" }, { label: "Reported By", cls: "" },
  { label: "Offense Category", cls: "" }, { label: "Date Reported", cls: "" },
  { label: "Review", cls: "text-end pe-4" }
];

const CategoryBadge = ({ category }) => {
  let theme = "warning";
  if (category === "Abusive Language") theme = "danger";
  if (category === "Inappropriate Content") theme = "danger";
  
  return (
    <span className={`badge bg-${theme} bg-opacity-10 text-${theme} border border-${theme} border-opacity-25 px-2 py-1 rounded-2`}>
      {category}
    </span>
  );
};

const ActionBtn = ({ icon, title, onClick, colorClass = "text-primary" }) => (
  <button onClick={onClick} className={`btn btn-sm mx-auto btn-light border-0 rounded-circle transition-hover ${colorClass} d-flex align-items-center justify-content-center`} style={{ width: "36px", height: "36px" }} title={title}>
    {icon}
  </button>
);

const getInitials = (name) => {
  const parts = name.trim().split(" ");
  return parts.length >= 2 ? `${parts[0][0]}${parts[1][0]}`.toUpperCase() : name.substring(0, 2).toUpperCase();
};

const SuspendModal = ({ report, onClose, onConfirm }) => {
  const [duration, setDuration] = useState("1 Week");
  const [adminRemarks, setAdminRemarks] = useState("");

  if (!report) return null;

  // Auto-fill the admin remarks with a professional summary of the faculty's claim
  const preFilledRemark = `Suspended for ${report.category} in ${report.assignment}. Specifically: ${report.remarks}`;

  const handleSubmit = (e) => {
    e.preventDefault();
    onConfirm(report.id);
  };

  return (
    <div className="position-fixed top-0 start-0 w-100 h-100 d-flex align-items-center justify-content-center" style={{ backgroundColor: "rgba(15, 23, 42, 0.6)", backdropFilter: "blur(4px)", zIndex: 1060 }}>
      <div className="bg-white rounded-4 shadow-lg w-100 overflow-hidden fade-in" style={{ maxWidth: "500px" }}>
        
        <div className="bg-danger bg-opacity-10 p-4 border-bottom border-danger border-opacity-25 d-flex justify-content-between align-items-center">
          <div className="d-flex align-items-center gap-3">
            <div className="bg-danger text-white rounded-circle d-flex align-items-center justify-content-center" style={{ width: "40px", height: "40px" }}>
              {ICONS.ban}
            </div>
            <div>
              <h5 className="fw-bold text-danger mb-0">Finalize Suspension</h5>
              <span className="text-danger small opacity-75">{report.student.name} ({report.student.rollNo})</span>
            </div>
          </div>
          <button type="button" className="btn btn-link text-danger p-0" onClick={onClose}>{ICONS.close}</button>
        </div>
        
        <form onSubmit={handleSubmit} className="p-4 p-md-5">
          <div className="mb-4">
            <label className="form-label fw-bold small text-muted">Suspension Duration *</label>
            <select className="form-select form-select-lg bg-light border-0 fs-6 text-dark" value={duration} onChange={e => setDuration(e.target.value)}>
              <option value="3 Days">3 Days</option>
              <option value="1 Week">1 Week</option>
              <option value="1 Month">1 Month</option>
              <option value="Permanent">Permanent (Expulsion)</option>
            </select>
          </div>

          <div className="mb-4">
            <label className="form-label fw-bold small text-muted">Official Reason (Sent to Student) *</label>
            <textarea 
              className="form-control bg-light border-0 fs-6" 
              rows="4" 
              defaultValue={adminRemarks || preFilledRemark}
              onChange={e => setAdminRemarks(e.target.value)}
              required
            ></textarea>
          </div>

          <div className="d-flex justify-content-end gap-2 mt-4">
            <button type="button" className="btn btn-light fw-medium px-4" onClick={onClose}>Cancel</button>
            <button type="submit" className="btn btn-danger fw-bold px-4">Enforce Suspension</button>
          </div>
        </form>
      </div>
    </div>
  );
};

const ReviewDrawer = ({ report, onClose, onDismiss, onProceedToSuspend }) => {
  if (!report) return null;

  return (
    <div className="position-fixed top-0 start-0 w-100 h-100 d-flex justify-content-end" style={{ backgroundColor: "rgba(15, 23, 42, 0.4)", backdropFilter: "blur(2px)", zIndex: 1050 }}>
      <div className="bg-white h-100 shadow-lg d-flex flex-column drawer-slide" style={{ width: "100%", maxWidth: "450px" }}>
        
        <div className="p-4 d-flex justify-content-between align-items-center border-bottom">
          <h5 className="fw-bold text-dark mb-0">Review Disciplinary Report</h5>
          <button className="btn btn-light rounded-circle p-2 text-secondary d-flex align-items-center justify-content-center" onClick={onClose}>{ICONS.close}</button>
        </div>

        <div className="p-4 overflow-auto flex-grow-1 bg-light bg-opacity-50">
          
          {/* Target Student Identity */}
          <h6 className="fw-bold text-muted text-uppercase mb-3" style={{ fontSize: "0.75rem", letterSpacing: "0.5px" }}>Reported Student</h6>
          <div className="bg-white p-3 rounded-4 border shadow-sm d-flex align-items-center gap-3 mb-4">
            <div className="rounded-circle d-flex align-items-center justify-content-center fw-bold text-danger bg-danger bg-opacity-10" style={{ width: "48px", height: "48px", fontSize: "1rem" }}>
              {getInitials(report.student.name)}
            </div>
            <div>
              <h6 className="fw-bolder text-dark mb-1">{report.student.name}</h6>
              <div className="text-secondary small fw-medium">{report.student.rollNo} • {report.student.dept}</div>
            </div>
          </div>

          {/* The Accusation Details */}
          <h6 className="fw-bold text-muted text-uppercase mb-3" style={{ fontSize: "0.75rem", letterSpacing: "0.5px" }}>Incident Context</h6>
          <div className="bg-white p-4 rounded-4 border shadow-sm mb-4">
            <div className="mb-3">
              <span className="text-muted small d-block mb-1">Reported By:</span>
              <span className="fw-medium text-dark">{report.faculty}</span>
            </div>
            <div className="mb-3">
              <span className="text-muted small d-block mb-1">Violation Category:</span>
              <CategoryBadge category={report.category} />
            </div>
            <div className="mb-3">
              <span className="text-muted small d-block mb-1">Location of Incident:</span>
              <a href="#" className="text-primary text-decoration-none fw-medium d-flex align-items-center gap-1" style={{ fontSize: "0.9rem" }}>
                {report.assignment} {ICONS.link}
              </a>
            </div>
            <div className="p-3 bg-secondary bg-opacity-10 border rounded-3 fst-italic text-dark mt-2" style={{ fontSize: "0.95rem", borderLeft: "3px solid #94a3b8 !important" }}>
              "{report.remarks}"
            </div>
          </div>
        </div>

        {/* DECISION BUTTONS (Bottom Fixed) */}
        <div className="p-4 border-top bg-white d-flex gap-3">
          <button 
            className="btn btn-light border fw-medium flex-grow-1 text-secondary" 
            onClick={() => onDismiss(report.id)}
          >
            Dismiss Report
          </button>
          <button 
            className="btn btn-danger fw-bold flex-grow-1 d-flex justify-content-center align-items-center gap-2 shadow-sm" 
            onClick={onProceedToSuspend}
          >
            {ICONS.ban} Suspend Student
          </button>
        </div>

      </div>
    </div>
  );
};

const ReportedStudents = () => {
  const [searchQuery, setSearchQuery] = useState("");
  const [queue, setQueue] = useState(mockReports);
  
  const [activeReportId, setActiveReportId] = useState(null);
  const [isSuspendModalOpen, setIsSuspendModalOpen] = useState(false);

  // Filter Logic
  const filteredQueue = useMemo(() => {
    const q = searchQuery.toLowerCase();
    return queue.filter(r => 
      r.student.name.toLowerCase().includes(q) || 
      r.student.rollNo.toLowerCase().includes(q) || 
      r.faculty.toLowerCase().includes(q)
    );
  }, [searchQuery, queue]);

  const activeReport = queue.find(r => r.id === activeReportId);

  // --- ACTIONS ---
  const handleDismiss = (id) => {
    setQueue(prev => prev.filter(r => r.id !== id));
    setActiveReportId(null);
    toast.success("Report dismissed. The faculty member has been notified of your decision.");
  };

  const handleFinalizeSuspension = (id) => {
    setQueue(prev => prev.filter(r => r.id !== id));
    setIsSuspendModalOpen(false);
    setActiveReportId(null);
    toast.error("Student suspended successfully. They have been moved to the Appeals queue.");
  };

  return (
    <div className="RS-container fade-in position-relative">

      {/* HEADER */}
      <div className="text-center mt-5 mb-4">
        <h1 className="fw-bolder text-dark mb-2" style={{ letterSpacing: "-0.5px" }}>Report Request Queue</h1>
        <p className="text-muted fw-medium fs-6">Review Terms of Service violations flagged by academic staff.</p>
      </div>

      {/* MAIN CARD */}
      <div className="card px-4 px-md-5 border-0 pb-5">
        
        {/* Dynamic Queue Counter */}
        {queue.length > 0 ? (
          <div className="d-flex justify-content-between align-items-end mb-3 px-1">
            <span className="text-secondary fw-semibold text-uppercase" style={{ fontSize: "0.8rem", letterSpacing: "0.5px" }}>
              Pending Reports
            </span>
            <span className="badge bg-warning bg-opacity-25 text-danger rounded-pill px-3 py-2">{queue.length} Awaiting Review</span>
          </div>
        ) : (
          <div className="mb-3 px-1" style={{ height: "24px" }}></div> // Spacer
        )}

        <div className="bg-light rounded-4 overflow-hidden border d-flex flex-column">
          
          {/* TOOLBAR */}
          <div className="p-3 border-bottom">
            <div className="position-relative w-100" style={{ maxWidth: "400px" }}>
              <span className="position-absolute top-50 translate-middle-y ms-3 text-secondary">{ICONS.search}</span>
              <input 
                type="text" className="w-100 bg-secondary bg-opacity-10 border rounded-3 ps-5 py-2 fw-light focus-ring focus-ring-secondary" 
                placeholder="Search by student or reporting faculty..." value={searchQuery} onChange={(e) => setSearchQuery(e.target.value)}
              />
            </div>
          </div>

          {/* QUEUE TABLE */}
          <div className="table-responsive flex-grow-1">
            <table className="table table-hover align-middle mb-0">
              <thead className="table-light">
                <tr>
                  {TABLE_HEADERS.map(({ label, cls }, idx) => (
                    <th key={idx} className={`text-uppercase text-muted py-3 border-bottom-0 ${cls}`} style={{ fontSize: "0.75rem", letterSpacing: "0.08em" }}>{label}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {filteredQueue.length > 0 ? (
                  filteredQueue.map((report) => (
                    <tr key={report.id} style={{ cursor: "pointer" }} onClick={() => setActiveReportId(report.id)}>
                      <td className="ps-4 py-3 border-light">
                        <div className="d-flex align-items-center gap-3">
                          <div className="rounded-circle d-flex align-items-center justify-content-center fw-bold text-danger bg-danger bg-opacity-10" style={{ width: "40px", height: "40px", fontSize: "0.85rem" }}>
                            {getInitials(report.student.name)}
                          </div>
                          <div>
                            <div className="fw-bold text-dark">{report.student.name}</div>
                            <div className="text-muted small">{report.student.rollNo}</div>
                          </div>
                        </div>
                      </td>
                      <td className="border-light text-dark fw-medium">{report.faculty}</td>
                      <td className="border-light">
                        <CategoryBadge category={report.category} />
                      </td>
                      <td className="border-light text-secondary small fw-medium">{report.date}</td>
                      <td className="border-0" onClick={(e) => e.stopPropagation()}>
                        <ActionBtn icon={ICONS.eye} title="Review Report Details" onClick={() => setActiveReportId(report.id)} />
                      </td>
                    </tr>
                  ))
                ) : (
                  <tr>
                    <td colSpan="5" className="text-center py-5">
                      <div className="text-success mb-3 mt-4" style={{ transform: "scale(2)" }}>{ICONS.check}</div>
                      <h5 className="fw-bold text-dark">Inbox Zero</h5>
                      <p className="text-muted m-0">There are no pending disciplinary reports to review.</p>
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>
      </div>

      {/* OVERLAYS */}
      <ReviewDrawer 
        report={activeReport} 
        onClose={() => setActiveReportId(null)} 
        onDismiss={handleDismiss} 
        onProceedToSuspend={() => setIsSuspendModalOpen(true)} 
      />
      
      {isSuspendModalOpen && (
        <SuspendModal 
          report={activeReport} 
          onClose={() => setIsSuspendModalOpen(false)} 
          onConfirm={handleFinalizeSuspension} 
        />
      )}

      <style>{`
        @keyframes slideInRight { from { transform: translateX(100%); } to { transform: translateX(0); } }
        .drawer-slide { animation: slideInRight 0.3s ease; }
      `}</style>
    </div>
  );
};

export default ReportedStudents;